### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Ywenjun123** [abhi1kumar/DEVIANT#11]
Where is your visualized code

**Comment by abhi1kumar** [comment]
Hi @Ywenjun123 
Thank you for your interest in DEVIANT. The visualization code is mentioned in the qualitative plots in the README at this [link](https://github.com/abhi1kumar/DEVIANT#qualitative-plotsvisualization)

The code is 
```bash
python plot/plot_qualitative_output.py --dataset waymo --folder output/run_1051/results_test/data
```
