### ISSUE TITLE
Nuscenes evalution

### ISSUE THREAD

**Issue by mingyuShin** [abhi1kumar/DEVIANT#13]
Thanks for your great work!

Do you happen to know methods for evaluating nuScenes using metrics other than MAE, such as mAP in your code?

**Comment by abhi1kumar** [comment]
Hi @mingyuShin 
Thank you for showing interest in DEVIANT again. To obtain the nuScenes  mAP and NDS numbers for:

- **Front images**: You could run our [patched nuscenes devkit](https://github.com/abhi1kumar/nuscenes-devkit). The instructions are [here](https://github.com/abhi1kumar/nuscenes-devkit/blob/master/convert_nuscenes_to_kitti_format_and_evaluate.sh#L73-L100).

- **All images**: Run the [original nuscenes devkit](https://github.com/nutonomy/nuscenes-devkit). The instructions are similar to [here](https://github.com/abhi1kumar/nuscenes-devkit/blob/master/convert_nuscenes_to_kitti_format_and_evaluate.sh#L73-L100).

Also, if you find our repo helpful, please consider starring our DEVIANT repo .

**Comment by mingyuShin** [comment]
Thank you for being so kind!
