### ISSUE TITLE
How to use a  row picture to validate the model?

### ISSUE THREAD

**Issue by Aangss** [abhi1kumar/DEVIANT#18]
Thank for your outstanding work. I have finished training the model, how do I validate the model using the original images or videos?  Can you give me  some advice?

**Comment by abhi1kumar** [comment]
Hi @Aangss 
Thank you for your interest in DEVIANT.

> I have finished training the model, how do I validate the model using the original images or videos? Can you give me some advice?

My hunch is you wanted to be sure if your model has converged well. I could think of following ways:
1. **AP**: If you have GT available, consider getting AP numbers similar to KITTI, Waymo or nuScenes dataset.
2. **Depth**: As stated in the paper, depth remains the hardest parameter to estimate for monocular 3D detection task. You could report MAE error on the TP boxes (boxes which has 2D IoU > 0.7 with the GT similar to Tab. 6 of our paper)
3. **Qualitative**: You could use our visualization scripts to plot the boxes in frontal view and BEV on random images of the dataset.

**Comment by Aangss** [comment]
Thank for your answer. But I'd like to verify the model using pictures I've taken myself,can I do that?   Or if I use the original photo or video, does the photo/video format need to be changed?

**Comment by abhi1kumar** [comment]
> I'd like to verify the model using pictures I've taken myself,can I do that? Or if I use the original photo or video, does the photo/video format need to be changed?

You can do that but that requires the following:
- Prepare your dataset in the  following order:
```
├── data
│      ├── Your_dataset
│      │      ├── ImageSets
│      │      └── testing
│      │            ├── calib
│      │            └── image_2
```
- The `image_2` folder contains your images in `.png` format.

- The `calib` contains camera calibration (intrinsics) as the following line: `P2` as `1x12` matrix. If you do not have camera calibration, use the following approximate COCO intrinsics from height `h` and width `w` of your image.

```python
import numpy as np
def get_intrinsics(h, w):
    intrinsic_matrix = np.zeros((3,4))
    f = 2 * h
    intrinsic_matrix[0, 0] = f
    intrinsic_matrix[1, 1] = f
    intrinsic_matrix[0, 2] = w / 2.0
    intrinsic_matrix[1, 2] = h / 2.0
    intrinsic_matrix[2, 2] = 1

    return intrinsic_matrix.flatten().tolist()
```
- Take your trained model and run the testing script.
- Finally run the visualization script `plot/plot_qualitative_output.py`. If you want videos, combine the frames together.

**Comment by Aangss** [comment]
@abhi1kumar Thanks for your advice,I will try it.

**Comment by Aangss** [comment]
@abhi1kumar  I'm so sorry to bother you. I completed the above steps, but the visualization seems to be bad,can you give me some advice?
![000001](https://github.com/abhi1kumar/DEVIANT/assets/144333787/8e33cff3-af0a-4c77-a0e9-48a525470eba)

**Comment by abhi1kumar** [comment]
Let us do it step by step. Can you show share the screenshot of the directory structure and paste the content of your calibration file here?

**Comment by Aangss** [comment]
Okay. I have pasted the information as follows

![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/433ea1d7-f2ed-4fbb-8575-1abfc939a2f3)

This is the contents of the 000001 txt file:
P0: 3.400000000e+03 0.000000000e+00 6.380000000e+02 0.000000000e+00 0.000000000e+00 3.400000000e+03 8.510000000e+02 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00
P1: 3.400000000e+03 0.000000000e+00 6.380000000e+02 0.000000000e+00 0.000000000e+00 3.400000000e+03 8.510000000e+02 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00
P2: 3.400000000e+03 0.000000000e+00 6.380000000e+02 0.000000000e+00 0.000000000e+00 3.400000000e+03 8.510000000e+02 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00
P3: 3.400000000e+03 0.000000000e+00 6.380000000e+02 0.000000000e+00 0.000000000e+00 3.400000000e+03 8.510000000e+02 0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00
These photos were all taken by ipone13,and P0-P3 were all converted to SciTech by generating a 12×1 matrix from the code you provided!

**Comment by abhi1kumar** [comment]
Thank you. The calibration files look OK to me. I believe the image resolution is `hxw = 680x1276`. Let us say you want to run over the Waymo (`run_1051`) model.

1. Change the input resolution in the [config](https://github.com/abhi1kumar/DEVIANT/blob/main/code/experiments/run_1051.yaml#L8) from `768x512` to `960x512` (to maintain the same aspect ratio).
2. Finally type the following:
```bash
CUDA_VISIBLE_DEVICES=0 python -u tools/train_val.py --config=experiments/run_1051.yaml --resume_model output/run_1051/checkpoints/checkpoint_epoch_30.pth -e
```  
3. You should see some text files in the `output/run_1051` directory. These should be our predictions. I hope these are non-empty
4. Finally, use the visualization scripts.

**Comment by Aangss** [comment]
If I want to run a KITTI model, is that the same thing?  I've only used kitti before.

**Comment by abhi1kumar** [comment]
> If I want to run a KITTI model, is that the same thing? I've only used kitti before.

You could try the waymo model first. The KITTI model is trained on `3.7k` images, while the waymo model is trained on  more than `50k` images (which makes it more robust). Hopefully, my waymo dataloader does not break.

**Comment by Aangss** [comment]
Okay,I will try it.  Need to change the dataset' name in config? Having just started first grade, your paper was the first one I read and I want to reproduce it to the best of my ability. But as of right now, I seem to suck at it.

**Comment by abhi1kumar** [comment]
> Okay,I will try it. 

Please let us know if you could run inference on other dataset images.

> Need to change the dataset' name in config? 

Check the paths and see if the images, calibs are being read.

> Having just started first grade, your paper was the first one I read and I want to reproduce it to the best of my ability. 

You should start with our released KITTI pretrained-models on KITTI and see if you could reproduce the KITTI numbers on your end. Then, move to cross-dataset experiment of KITTI model on nuScenes. And finally to your own custom dataset.

**Comment by Aangss** [comment]
Sorry, I wasn't able to test the model on my own dataset image, I think some of my paths weren't modified correctly causing it to still be a KITTI dataset when performing the inference process. Can you tell me exactly where to modify the paths to put into my own dataset? Thanks.

**Comment by abhi1kumar** [comment]
Change the `eval_dataset` in the following KITTI config: Change this [line](https://github.com/abhi1kumar/DEVIANT/blob/main/code/experiments/run_221.yaml#L9) to `YSS_data`

Then, see if the code goes to the following lines of [KITTI dataloader](https://github.com/abhi1kumar/DEVIANT/blob/main/code/lib/datasets/kitti.py#L59-L62)

Before doing this part, were you able to reproduce our KITTI numbers with the pre-trained model on your end? That will indicate that you have setup the environment correctly.

**Comment by Aangss** [comment]
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/73d73aa2-20ff-4bbb-9c41-57e8bcc0825d)
I reproduced the pre-trained model with some of the KITTI images, I think the environment should be fine.
But when I run the test script, the following error is reported


2023-11-09 10:01:30,021   INFO  ==> Loading from checkpoint 'output/run_221/checkpoints/checkpoint_epoch_140.pth'
2023-11-09 10:01:32,223   INFO  ==> Done
Evaluation Progress:   0%|                                                                                                                     | 0/52 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train_val.py", line 159, in <module>
    main()
  File "tools/train_val.py", line 135, in main
    tester.test()
  File "/home/yss/DEVIANT/code/lib/helpers/tester_helper.py", line 50, in test
    for batch_idx, (inputs, calibs, coord_ranges, _, info) in enumerate(self.data_loader):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 104, in __getitem__
        img = self.get_image(index)
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 82,  in get_image
        assert os.path.exists(img_file)
AssertionError

**Comment by Aangss** [comment]
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/73d73aa2-20ff-4bbb-9c41-57e8bcc0825d)
I reproduced the pre-trained model with some of the KITTI images, I think the environment should be fine.
But when I run the test script, the following error is reported


2023-11-09 10:01:30,021   INFO  ==> Loading from checkpoint 'output/run_221/checkpoints/checkpoint_epoch_140.pth'
2023-11-09 10:01:32,223   INFO  ==> Done
Evaluation Progress:   0%|                                                                                                                     | 0/52 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train_val.py", line 159, in <module>
    main()
  File "tools/train_val.py", line 135, in main
    tester.test()
  File "/home/yss/DEVIANT/code/lib/helpers/tester_helper.py", line 50, in test
    for batch_idx, (inputs, calibs, coord_ranges, _, info) in enumerate(self.data_loader):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 104, in __getitem__
        img = self.get_image(index)
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 82,  in get_image
        assert os.path.exists(img_file)
AssertionError

**Comment by Aangss** [comment]
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/73d73aa2-20ff-4bbb-9c41-57e8bcc0825d)
I reproduced the pre-trained model with some of the KITTI images, I think the environment should be fine.
But when I run the test script, the following error is reported


2023-11-09 10:01:30,021   INFO  ==> Loading from checkpoint 'output/run_221/checkpoints/checkpoint_epoch_140.pth'
2023-11-09 10:01:32,223   INFO  ==> Done
Evaluation Progress:   0%|                                                                                                                     | 0/52 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train_val.py", line 159, in <module>
    main()
  File "tools/train_val.py", line 135, in main
    tester.test()
  File "/home/yss/DEVIANT/code/lib/helpers/tester_helper.py", line 50, in test
    for batch_idx, (inputs, calibs, coord_ranges, _, info) in enumerate(self.data_loader):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/.conda/envs/ysbt/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 104, in __getitem__
        img = self.get_image(index)
  File "/home/yss/DEVIANT/code/lib/datasets/kitti.py", line 82,  in get_image
        assert os.path.exists(img_file)
AssertionError

**Comment by abhi1kumar** [comment]
> os.path.exists(img_file)

Can you check the image_paths and print out the path which the dataloader is looking for and is not able to find.

**Comment by Aangss** [comment]
2023-11-09 10:36:19,195   INFO  ==> Loading from checkpoint 'output/run_221/checkpoints/checkpoint_epoch_140.pth'
2023-11-09 10:36:21,446   INFO  ==> Done
Evaluation Progress:   0%|                                                                                                                     | 0/52 [00:00<?, ?it/s]Checking img_file: /home/yss/DEVIANT/code/data/YSS_data/validation/image/000000.png
Checking img_file: /home/yss/DEVIANT/code/data/YSS_data/validation/image/000002.png
Checking img_file: /home/yss/DEVIANT/code/data/YSS_data/validation/image/000004.pngChecking img_file: /home/yss/DEVIANT/code/data/YSS_data/validation/image/000006.png

**Comment by abhi1kumar** [comment]
> Checking img_file: /home/yss/DEVIANT/code/data/YSS_data/validation/image/000006.png

This is different from the path I had suggested. You should rename the `testing` folder to `validation` and `image_2` folder to `image`.  The final structure is now as follows:

```bash
├── data
│      ├── YSS_data
│      │      ├── ImageSets
│      │      └── validation
│      │            ├── calib
│      │            ├── image
│      │            └── label
```
Would you mind trying once again after renaming your folders?

**Comment by Aangss** [comment]
ok, I will try

**Comment by Aangss** [comment]
But does the validation set's label also need to have content?

**Comment by abhi1kumar** [comment]
> But does the validation set's label also need to have content?

Only if you need to evaluate against the GT.

**Comment by Aangss** [comment]
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/41b8cbcb-c668-4d44-86f2-0a8bc2bfe5b8)
Why does the generated result visualize the output image as it was during training?   Generated results Why does the visualization output the image as it was during training? The visualization program I have modified.
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/97276d83-5af6-4f86-8320-66035ada3f05)

**Comment by abhi1kumar** [comment]
Do you see some results in these text files? or are these files empty?

> Why does the generated result visualize the output image as it was during training? 

The visualization code is only for KITTI, Waymo or nusc_KITTI datasets, and not for your custom dataset which has different sizes than these datasets. 

Consider extending `plot/plot_qualitative_output.py` for your own dataset.

**Comment by Aangss** [comment]
These files are not empty, there are some results.

**Comment by Aangss** [comment]
I tried to put some test photos from KITTI into YSS as I recall and evaluated them with config221 and the output file seems to be ok . 
Here are the results of my attempts to visualize the results, the evaluation did not plot correctly in the YSS plot, it seems that, as you say, I need to  extend my own dataset in the visualization scripts

![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/a8e108a1-6537-4efe-8740-e1b3e3694428)
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/eb03419f-cf5d-4e5d-a24a-3f70075c56f2)
It stands to reason that the plotting of the following figure should be in the upper figure. That's just my personal opinion.

**Comment by Aangss** [comment]
This is the result of my visualization of the YSS dataset using KITTI model.(run_221)  It seems that the resolution is quite important for the visualization result, I don't know how to modify the proper resolution with the P2 matrix, can you please give me some suggestions? Thank you very much!
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/0263cf5b-6213-4f9a-b457-2387ef8ffaf0)
P2:  3.404000000000e+03 0.000000000000e+00 6.380000000000e+02 0.000000000000e+00 0.000000000000e+00 3.404000000000e+03 8.510000000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
