### ISSUE TITLE
Waymo Dataset  Version

### ISSUE THREAD

**Issue by wbzheng11** [abhi1kumar/DEVIANT#20]
Does the waymo model use the [V1.1 version](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_1_0) released by the official website? 

What should I use if I downloaded version 1.0?

Thank you！

**Comment by abhi1kumar** [comment]
Thank you for your interest in DEVIANT.

> Does the waymo model use the [V1.1 version](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_1_0) released by the official website?

Yes, the waymo models use the V1.1

> What should I use if I downloaded version 1.0?

We have not tested with the other versions. Therefore, you should download the correct version i.e. V1.1 as mentioned in our [FAQ](https://github.com/abhi1kumar/DEVIANT#faq)

**Comment by wbzheng11** [comment]
Thank you for your answer and best wishes.
